version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - php

  php:
    build: .
    container_name: php_container
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: padel-league
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
